apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rendered/external-secrets.yaml
  - resources/cluster-secret-store-aws-ssm.yaml
  - resources/minio-creds-access-keys.yaml
