apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rendered/minio.yaml
  - resources/job_seed_minio_terraform_cache.yaml

patches:
  - path: patches/fix-bug-script-volume-permissions.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: minio
      namespace: argo
