apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-dev-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: eso-dev-aws-creds
            namespace: external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: eso-dev-aws-creds
            namespace: external-secrets
            key: secret-access-key
