- op: replace
  path: /spec/template/spec/initContainers/0/args/1
  value: |
    paths=()
    paths+=("/bitnami/minio/data")
    for path in "${paths[@]}"; do
      mkdir -p "$path"

      ls -hal "$path"

      chown 1001:1001 "$path" || true
      chmod 2770 "$path" || true

      ls -hal "$path"

      find "$path" -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
        xargs -r chown -R 1001:1001

      ls -hal "$path"
    done
