apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rendered/argo-workflows.yaml
  - resources/artifact-repositories.yaml
  - resources/rbac-argo-workflow-runner.yaml

patches:
  - path: patches/set-argo-server-auth-mode.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-server
      namespace: argo
  - path: patches/workflow-controller-configmap.yaml
    target:
      version: v1
      kind: ConfigMap
      name: workflow-controller-configmap
      namespace: argo
